### ISSUE TITLE
Helo announcement domain name mismatch

### ISSUE THREAD

**Issue by bagofjuice** [davidepedranz/docker-send-only-postfix#2]
I was doing some debugging using mail-tester.com, and found some issues.

My docker-compose config is something like:
```
  postfix:
    image: davidepedranz/docker-send-only-postfix
    container_name: postfix
    restart: always
    environment:
      - DOMAIN=mydomain.co.uk
```

The FQDN announced by the Helo command uses the docker id as the sub domain:

> Here are the tested values for this check:
> IP: xxx.xxx.xxx.xxx
> HELO: 05bbce513072.mydomain.co.uk
> rDNS: mydomain.co.uk

This also results in:
> We didn't find a server (A Record) behind your hostname 05bbce513072.mydomain.co.uk.
